apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

configMapGenerator:
- name: nginxconfig
  files:
  - nginx.conf

secretGenerator:
  - name: env_file_secret
    envs:
    - secrets.txt
    type: Opaque

images:
- name: nginx
  newName: my-registry/nginx
  newTag: v1

replicas:
- name: nginx
  count: 2

commonLabels:
  env: dev
